### ISSUE TITLE
Stopped working with React 18

### ISSUE THREAD

**Issue by josefnorlin** [wouterds/react-native-tv-focus#1]
Hi Wouterds!

Found this package and was thrilled. It filled the gap we had with React Native tvOS for AndroidTV.

But now when I updated to React 18 and react-native-tvos 0.69.6-2 it stopped working. Have any one else exerienced this?

**Comment by wouterds** [comment]
Hi @josefnorlin, as far as I know it's related to an issue upstream in `react-native-tvos`. I noticed the same, underlying this package makes use of the `hasTVPreferredFocus` prop which seems to be broken since > 0.66.

- https://github.com/react-native-tvos/react-native-tvos/issues/398
- https://github.com/react-native-tvos/react-native-tvos/issues/380

**Comment by josefnorlin** [comment]
Thank you @wouterds! Then we can close this and I will subscribe to the progress on those.
